### ISSUE TITLE
Not working on mobile view

### ISSUE THREAD

**Issue by ateev** [loktar00/react-lazy-load#59] opened 2016-04-22 13:13 UTC
@sergeylaptev  I am using Lazy Loader on desktop. It works perfectly. But on a smaller screen, it isn't. All images are getting loaded even if not in the viewport. What is going wrong here ?

[Link](https://www.practo.com/healthfeed/life-lessons-on-winning-from-losing-12961/post)

**Comment by mull** [comment] 2016-10-05 12:02
@ateev @loktar00 has this been resolved?

**Comment by Juliiii** [comment] 2017-07-19 04:43
I have the same problems now, making me very upset. so has this been resolved? @ateev

**Comment by BosenY** [comment] 2018-09-28 02:52
The same problem with you @ateev

**Comment by eagle1000** [comment] 2021-04-16 19:43
Has anyone ever solved this issue?  The issue is now 5 years old I noticed.  I started using this library recently and am experiencing the same issues as @ateev  originally described.

**Comment by loktar00** [comment] 2022-08-29 02:35
Should work  now with 4.0, but will keep this open so I an test and make sure, just commented so I remember.

**Comment by loktar00** [comment] 2022-08-29 17:30
Just tested on mobile (chrome on android) seems to work well. Closing for now if you notice it not working definitely feel free to reopen.

**Closed by loktar00** 2022-08-29 17:30 UTC
Labels: bug
